const EVOLUTIONS = {
  "bulbasaur":{
    "level":"16",
    "to":"ivysaur"
  },
  "ivysaur":{
    "level":"32",
    "to":"venusaur"
  },
  "charmander":{
    "level":"16",
    "to":"charmeleon"
  },
  "charmeleon":{
    "level":"36",
    "to":"charizard"
  },
  "squirtle":{
    "level":"16",
    "to":"wartortle"
  },
  "wartortle":{
    "level":"36",
    "to":"blastoise"
  },
  "caterpie":{
    "level":"7",
    "to":"metapod"
  },
  "metapod":{
    "level":"10",
    "to":"butterfree"
  },
  "weedle":{
    "level":"7",
    "to":"kakuna"
  },
  "kakuna":{
    "level":"10",
    "to":"beedrill"
  },
  "pidgey":{
    "level":"18",
    "to":"pidgeotto"
  },
  "pidgeotto":{
    "level":"36",
    "to":"pidgeot"
  },
  "rattata":{
    "level":"20",
    "to":"raticate"
  },
  "spearow":{
    "level":"20",
    "to":"fearow"
  },
  "ekans":{
    "level":"22",
    "to":"arbok"
  },
  "pikachu":{
    "level":"35",
    "to":"raichu"
  },
  "sandshrew":{
    "level":"22",
    "to":"sandslash"
  },
  "nidoran f":{
    "level":"16",
    "to":"nidorina"
  },
  "nidorina":{
    "level":"35",
    "to":"nidoqueen"
  },
  "nidoran m":{
    "level":"16",
    "to":"nidorino"
  },
  "nidorino":{
    "level":"35",
    "to":"nidoking"
  },
  "clefairy":{
    "level":"35",
    "to":"clefable"
  },
  "vulpix":{
    "level":"35",
    "to":"ninetales"
  },
  "jigglypuff":{
    "level":"35",
    "to":"wigglytuff"
  },
  "zubat":{
    "level":"22",
    "to":"golbat"
  },
  "oddish":{
    "level":"21",
    "to":"gloom"
  },
  "gloom":{
    "level":"35",
    "to":"vileplume"
  },
  "paras":{
    "level":"24",
    "to":"parasect"
  },
  "venonat":{
    "level":"31",
    "to":"venomoth"
  },
  "diglett":{
    "level":"26",
    "to":"dugtrio"
  },
  "meowth":{
    "level":"28",
    "to":"persian"
  },
  "psyduck":{
    "level":"33",
    "to":"golduck"
  },
  "mankey":{
    "level":"28",
    "to":"primeape"
  },
   "growlithe":{
    "level":"35",
    "to":"arcanine"
  },
  "poliwag":{
    "level":"25",
    "to":"poliwhirl"
  },
  "poliwhirl":{
    "level":"50",
    "to":"poliwrath"
  },
  "abra":{
    "level":"16",
    "to":"kadabra"
  },
  "kadabra":{
    "level":"40",
    "to":"alakazam"
  },
  "machop":{
    "level":"28",
    "to":"machoke"
  },
  "machoke":{
    "level":"40",
    "to":"machamp"
  },
  "bellsprout":{
    "level":"21",
    "to":"weepinbell"
  },
  "weepinbell":{
    "level":"35",
    "to":"victreebel"
  },
  "tentacool":{
    "level":"30",
    "to":"tentacruel"
  },
  "geodude":{
    "level":"25",
    "to":"graveler"
  },
  "graveler":{
    "level":"40",
    "to":"golem"
  },
  "ponyta":{
    "level":"40",
    "to":"rapidash"
  },
  "slowpoke":{
    "level":"37",
    "to":"slowbro"
  },
  "magnemite":{
    "level":"30",
    "to":"magneton"
  },
  "doduo":{
    "level":"31",
    "to":"dodrio"
  },
  "seel":{
    "level":"34",
    "to":"dewgong"
  },
  "grimer":{
    "level":"38",
    "to":"muk"
  },
  "shellder":{
    "level":"35",
    "to":"cloyster"
  },
  "gastly":{
    "level":"25",
    "to":"haunter"
  },
  "haunter":{
    "level":"40",
    "to":"gengar"
  },
  "drowzee":{
    "level":"26",
    "to":"hypno"
  },
  "krabby":{
    "level":"28",
    "to":"kingler"
  },
  "voltorb":{
    "level":"30",
    "to":"electrode"
  },
   "exeggcute":{
    "level":"35",
    "to":"exeggutor"
  },
  "cubone":{
    "level":"28",
    "to":"marowak"
  },
  "koffing":{
    "level":"35",
    "to":"weezing"
  },
  "rhyhorn":{
    "level":"42",
    "to":"rhydon"
  },
  "horsea":{
    "level":"32",
    "to":"seadra"
  },
  "goldeen":{
    "level":"33",
    "to":"seaking"
  },
  "staryu":{
    "level":"35",
    "to":"starmie"
  },
  "magikarp":{
    "level":"20",
    "to":"gyarados"
  },
  "eevee":{
    "level":"25",
    "to":"vaporeon"
  },
  "eevee":{
    "level":"27",
    "to":"jolteon"
  },
  "eevee":{
    "level":"29",
    "to":"flareon"
  },
  "omanyte":{
    "level":"40",
    "to":"omastar"
  },
  "kabuto":{
    "level":"40",
    "to":"kabutops"
  },
  "dratini":{
    "level":"30",
    "to":"dragonair"
  },
  "dragonair":{
    "level":"55",
    "to":"dragonite"
  },
  "chikorita":{
    "level":"16",
    "to":"bayleef"
  },
  "bayleef":{
    "level":"32",
    "to":"meganium"
  }
};
